# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the 'release' branch
  push:
    branches: [ 'develop', 'preview', 'release' ]
  pull_request:
    branches: [ 'develop', 'preview', 'release' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called 'build'
#   build:
#     # The type of runner that the job will run on
#     runs-on: self-hosted

#     # Define variables
#     env:
#       branch: ${{ github.ref_name }}
#       path: /var/www/html/${{ github.ref_name }}/TemplateReact/TemplateReactFront

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Print informations
#       - name: Print informations
#         run: |
#           echo '---------------------------------------'
#           echo "The current user: $(whoami)"
#           echo "The current repository: $(pwd)"
#           echo "The current branch: $branch"
#           echo "The folder path project: $path"
#           echo "The current version of npm: $(npm -v)"
#           echo '---------------------------------------'



#       # Install npm dependencies
#       - name: Install / Prune / Build project
#         run: npm i && npm prune && npm run build

#       # Delete the previous build
#       - name: Delete previous build
#         run: rm -rf $path

#       # Create new build directory
#       - name: Create new build directory
#         run: mkdir -p $path

#       # Move the new build to the directory
#       - name: Move new build
#         run: mv build/* $path